[package]
name = "mutable"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"

[[bench]]
name = "bench"
harness = false

[dependencies]
indexmap = "1.0"

[dev-dependencies]
criterion = "0.2"
rand = "0.6.5"